import { Inter } from "next/font/google";
import "./globals.css";
import { ContentWrapper, SidebarWrapper } from "fictoan-react";

const inter = Inter({ subsets : ["latin"] });

export const metadata = {
    title       : "FICTOAN docs",
    description : "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <SidebarWrapper></SidebarWrapper>
        <ContentWrapper>
            {children}
        </ContentWrapper>
        </body>
        </html>
    );
}
